### ISSUE TITLE
odfe-1.6.0.zip distribution missing Windows executables

### ISSUE THREAD

**Issue by johnthom** [opendistro-for-elasticsearch/opendistro-build#112]
The Windows zip file download for 1.6.0 is missing Windows java jdk\bin executables (DLLs and EXEs) and the other executables under the bin folder, i.e. -  elasaticsearch-service-mgr.exe, etc.  I first noticed this issue with 1.4.0.

ref url: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/odfe-windows/ode-windows-zip/odfe-1.6.0.zip

**Comment by peterzhuamazon** [comment]
Hi @johnthom,

After some researching, this issue is apparently fixed by Rashabh here:
#114

After testing odfe 1.4.0 manually on a EC2 Windows 2019 instance, it is confirmed that this issue has been fixed now.

Thanks for reporting the issue and we will close this issue for now.
Please feel free to re-open this issue if you have any other related questions.

Thanks.
