### ISSUE TITLE
ODFE release for Elastic search 7.6.2

### ISSUE THREAD

**Issue by Haneefh** [opendistro-for-elasticsearch/opendistro-build#117]
I would like to use ODFE for Elastic Search 7.6.2. The current version doesnt support it. Is there a workaround or when would be there a release for 7.6.2 version

**Comment by rosenjiang** [comment]
i have same issue.

**Comment by froggy75013** [comment]
I have same issue too.

**Comment by ankitde96** [comment]
I have same issue.

**Comment by weicongs-amazon** [comment]
Hi, @Haneefh @rosenjiang @Spykyx @ankitde96  7.6.2 isn't supported yet. but you can try the [Standalone Elasticsearch plugin installation way](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/) to install the plugins one by one with ES 7.6.2. But we are not 100% sure if they are fully compatible since we never test our plugins with 7.6.2.  Thanks

**Comment by weicongs-amazon** [comment]
close this issue. 7.6.2 support isn't in our plan now
