### ISSUE TITLE
Opendistroforelasticsearch-1.6.0.rpm fails to install if not connected to internet

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/opendistro-build#120]
Related to https://discuss.opendistrocommunity.dev/t/opendistroforelasticsearch-1-6-0-rpm-fails-to-install-if-not-connected-to-internet/2551.

**Comment by zeising** [comment]
Just a quick note to say that I've also run into this issue.

**Comment by akshayurdh** [comment]
I use internal repo and system does not have access to internet hence unable to install 1.6.0. I have to revert back to 1.4.0

**Comment by alolita** [comment]
Hi @vamshin @zeising @akshayurdh - Are you just trying to upgrade to 1.6.0 with the ODFE RPMs? Can you provide more details on your install?

**Comment by zeising** [comment]
Our elasticsearch environment does not have internet access, so we sync the RPMs to a local repository to install from. However, this does not work wiht 1.6.0 since it tries to fetch the KNNIndex library/plugin directly from the internet (from cloudfront). This library needs to be included in the RPM file.

**Comment by hensko** [comment]
The solution should be to include the kNN-library inside the opendistroforelasticsearch-1.6.0.rpm.
Using wget inside a rpm does not manage the permissions and rpm-database in a good way.
And if rpm handles the file, it will be removed upon uninstall, which is much better then the solution in the rpm today.

**Comment by zeising** [comment]
> The solution should be to include the kNN-library inside the opendistroforelasticsearch-1.6.0.rpm.
> Using wget inside a rpm does not manage the permissions and rpm-database in a good way.
> And if rpm handles the file, it will be removed upon uninstall, which is much better then the solution in the rpm today.

This sounds good to me.  I don't know exactly how to get the build infra to do this though, so I'm not able to make a PR, at least not right now.

**Comment by zeising** [comment]
Looking at this: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/linux_distributions/scripts/preInstall.sh which is the script that tries to fetch kNN, it should be enough, probably, to package libKNNIndexV1_7_3_6.so (or another version, if more appropriate) in the rpm (and deb, I guess) directly, instead of packaging the .zip and extracting that one.

**Comment by akshayurdh** [comment]
> Hi @vamshin @zeising @akshayurdh - Are you just trying to upgrade to 1.6.0 with the ODFE RPMs? Can you provide more details on your install?

We have a local repository where we sync all dependent ODFE rpms and then install/upgrade from our local repo. as and when required.

**Comment by Chivolta** [comment]
I have the same situation. Do you know any workaround?

**Comment by weicongs-amazon** [comment]
Hi, all
our team is working on fix the issue. In the meanwhile, one workaround you probably can try with:

 #Get all needed rpms
 sudo curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
 sudo yum install --downloadonly --downloaddir=opendistro-rpms opendistroforelasticsearch-1.7.0
 cd opendistro-rpms
 #Remove the opendistroforelasticsearch rpm
 sudo rm -rf opendistroforelasticsearch-1.7.0.rpm 

 #Get the libKNNIndexV1_7_3_6.so lib file
 wget https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip
 unzip libKNNIndexV1_7_3_6.zip

 #copy the rpms and lib file to servers of your cluster
 #install odfe
 sudo yum localinstall -y *.rpm
 #mv the libKNNIndexV1_7_3_6.so lib file to /usr/lib
 sudo mv libKNNIndexV1_7_3_6.so /usr/lib/
 sudo systemctl start elasticsearch.service
The key idea is that remove opendistroforelasticsearch-x.x.x.rpm and install the other RPMs and libKNNIndexV1_7_3_6 manually.

Here I used 1.7.0 ODFE version. it should be the same for other versions which include KNN plugin.

**Comment by WennySoft** [comment]
Hi,

as we do an automatic install the workaound would be somewhat complex. As we currently do not use this plugin: is there any possibility to skip this step completely?

Is there an estimation when this issue will be fixed - perhaps we could delay the update then....

Regards Michael

**Comment by weicongs-amazon** [comment]
@WennySoft For the RPM installation, I don't see a way to skip this plugin since it's a required plugin dependency, unless the plugin standalone installation is ok for your env.
For the fixing, we are trying to have it in our next release 1.8.1 https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/246  firstly.

**Comment by peterzhuamazon** [comment]
Status Update: KNN logic will be fixed in 1.9.0 release now. (https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/274)
