### ISSUE TITLE
opendistroforelasticsearch/opendistroforelasticsearch or amazon/opendistro-for-elasticsearch

### ISSUE THREAD

**Issue by an-sush** [opendistro-for-elasticsearch/opendistro-build#150]
As per Opendistro official [documentation](https://opendistro.github.io/for-elasticsearch/downloads.html), the docker image to be used is amazon/opendistro-for-elasticsearch. However, looking at the [github actions on this repo](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/31c89a095ef0bc4f4045b178102415fd595b1bf5/.github/workflows/webhook-build-docker.yml#L210), it seems the latest image is pushed to opendistroforelasticsearch/opendistroforelasticsearch. Can you please suggest difference between the two? Because I see a more recent version 1.7.0 under opendistroforelasticsearch and not under amazon/opendistro-for-elasticsearch.

**Comment by peterzhuamazon** [comment]
Hi @an-sush,

**opendistroforelasticsearch/opendistroforelasticsearch** is used for the _**test stage**_ for our internal verification before releasing to public.

**amazon/opendistro-for-elasticsearch** is the official docker hub that we used to offer customers the official latest releases, aka the _**release stage**_.

Please go ahead and use the image provided in amazon/opendistro-for-elasticsearch, which is also the hub we linked on our official website.
https://opendistro.github.io/for-elasticsearch/downloads.html

------

In order to avoid more confusions in the future, we have renamed our workflow files in this PR #157. As you see, we currently do not have an automate process for release stage action yet, and relies on manual steps. We will make sure to add release stage work flow in the future.

Thanks,
Peter
