### ISSUE TITLE
Automate cluster setup operations for ODFE releases

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/opendistro-build#240]
Automate the process to set up testing cluster for new ODFE release

**Comment by gaiksaya** [comment]
Testing clusters domain set up has been automated. You can find the clusters setup below:

## Single node testing cluster

- [ ] Test cluster set-up: Anyone can add this [workflow](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/.github/workflows/test-cluster-set-up.yml) to your repo/fork that uses the this [cloudformation template](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/.github/templates/odfe-testing-cluster-template.json) to set up the AWS resources in your account. ODFE and kibana are installed using the [userdata script](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/.github/scripts/userdata.sh). Please pass the necessary parameters as required.

- [ ] Static domain cluster set-up: Used for internal testing by plugin teams through out the release process. This set-up uses static domain names pre-configured by infra team so that clusters can be updated daily with recent artifacts without changing the domain names. Set-up can be found [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/.github/workflows/test-cluster-static-domain-set-up.yml)

### Multi-node testing cluster
_Coming soon_
