### ISSUE TITLE
Release ODFE 1.8.1 based on ES 7.7.1

### ISSUE THREAD

**Issue by weicongs-amazon** [opendistro-for-elasticsearch/opendistro-build#246]
ODFE 1.8.1 Release based on ES 7.7.1

**Comment by xinlamzn** [comment]
Required for the security fixes in 7.7.1.

**Comment by peterzhuamazon** [comment]
### Action Items: ###
- Make version bumps in preparation for 1.8.1 (PR #266)
- Update docker/KNN with the new processes (PR #265)
- More

**Comment by NicolasPSQ** [comment]
Hello, sorry, but this version will not be release?

Thanks

**Comment by WennySoft** [comment]
Hi,

we are impatiently waiting for this release in order to update our cluster (KNN-delivery-problem) in order to use the new kibana apis.

If this will not be released (as 1.9.0 is on the way?) - are there any information when a release will be available which contains the KNN-fix?

Regards Michael

**Comment by peterzhuamazon** [comment]
@NicolasPSQ @WennySoft As of now, we have proceed to work on 1.9.0 ODFE release with 7.8.0 ES.
As of the KNN fix, if you are talking about [this](https://github.com/opendistro-for-elasticsearch/k-NN/issues/154), it will be included in upcoming 1.9.0 release.
Thanks.

**Comment by NicolasPSQ** [comment]
Hi @peterzhuamazon ,
thanks for your work and for reply.
the new release 1.9.0 will include support for 7.7.1 or at this point is better to upgrade my elasticstack to 7.8.0 version?

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @NicolasPSQ as of now we are not working on ES 7.7.1 support.
If you need the security patch ([CVE-2020-7015](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7015)) for Kibana since 7.7.1+, you can choose to try out ODFE 1.9.0 once it comes out, since 7.8.0 will have it.

Once we release ODFE 1.9.0 you will be able to check the release notes for changes and new features, and decide whether you need them for your env to upgrade.

**Comment by peterzhuamazon** [comment]
ODFE 1.9.0 with ES 7.8.0 release now
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/274
