### ISSUE TITLE
Upgrade Opendistro to Previous versions - Dependency Issues

### ISSUE THREAD

**Issue by gferrette** [opendistro-for-elasticsearch/opendistro-build#341]
Hello,

I'm trying to upgrade Openditro from version 1.0.2 to version 1.7.0 with CENTOS 7. I'm following the docs as below but i'm getting dependency issues.

yum install opendistroforelasticsearch-1.7.0

Error: Package: opendistro-knn-1.7.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.6.1
           Removing: elasticsearch-oss-7.0.1-1.x86_64 (@elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Updated By: elasticsearch-oss-7.8.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.8.0-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)

Is there any way to upgrade Opendistro to previous versions? I've tested to upgrade to the last version and it was succesfull.

Thanks in advance.

Gabriel.

**Comment by peterzhuamazon** [comment]
Hi @gferrette sorry for the inconvenience here.
Seems like there is an issue with our docs on upgrading process, sorry about that.

Here is an option I test it myself to upgrade from 1.0.2 to 1.7.0.
Note that I use a wildcard due to 1.7.0 have plugin version all match to 1.7.0.0, not necessarily true for all releases:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/

``
sudo yum install yum-utils
sudo yumdownloader elasticsearch-oss-7.6.1
sudo yumdownloader opendistroforelasticsearch-1.7.0
sudo yumdownloader opendistro-*1.7.0.0
sudo yum install `ls | grep rpm`
``

I am seeing:
``
Installing:
opendistro-anomaly-detector   1.7.0.0-1
opendistro-index-management   1.7.0.0-1
opendistro-knn   1.7.0.0-1

Updating:
elasticsearch-oss   7.6.1-1
opendistro-alerting   1.7.0.0-1
opendistro-job-scheduler   1.7.0.0-1
opendistro-performance-analyzer   1.7.0.0-1
opendistro-security   1.7.0.0-0
opendistro-sql   1.7.0.0-1
opendistroforelasticsearch   1.7.0-1
``

NOTE: I have no data in my test and I recommended you to test this on another server with dummy data to check if data is correct after the upgrade.

Please let me know if you have any other questions.
I hope this could help you with your upgrade.

Thanks,
Peter

**Comment by gferrette** [comment]
Hello @peterzhuamazon !

I've tested this procedure that you have suggest on my test environment and it worked like a charm!

On saved objects now i see"Advanced Settings [7.0.1]" and "Advanced Settings [7.6.1]" after upgrade.

Do you know if i can delete "Advanced Settings [7.0.1]"?

![image](https://user-images.githubusercontent.com/44647577/89671176-e2ddf300-d8b8-11ea-91d5-986ac7ba7684.png)

Thank you very much for your quick answer!

Gabriel.

**Comment by peterzhuamazon** [comment]
Hi @gferrette I am not sure about this.
Where did you see this happening?
Could you show me the entire page?

**Comment by gferrette** [comment]
Hello @peterzhuamazon !

Sure, follow below the entire page, i saw that on Management->Saved Objects:

![image](https://user-images.githubusercontent.com/44647577/89676497-2557fd80-d8c2-11ea-848f-e02e526afe0b.png)

**Comment by peterzhuamazon** [comment]
Hi @gferrette could you show me the contents of both advanced settings?
If the contents of these saved objects do not affect normal usages, then you can just keep it there.

**Comment by gferrette** [comment]
Hello @peterzhuamazon !

Both advanced settings have the same content as example bellow, if I change something on one "Advanced settings" it is reflecting on the other one.

![image](https://user-images.githubusercontent.com/44647577/89682468-28a4b680-d8cd-11ea-9460-09d1d0d6d0ee.png)

**Comment by peterzhuamazon** [comment]
Hi @gferrette you can just leave it as it be, seems like it wont impact normal usages.
If you really want to remove it:
* We suggest you test the deletion on your test machine and see if there is any issues
* Make sure you export the saved objects as a backup before doing so:
   https://www.elastic.co/guide/en/kibana/current/managing-saved-objects.html#:~:text=Kibana%20are%20overwritten.-,Exportedit,and%20export%20objects%20by%20type

Thanks,
Peter

**Comment by gferrette** [comment]
Hello @peterzhuamazon !

Thanks a lot for this help.

I'm going to make those tests.

Att,

Gabriel.
