### ISSUE TITLE
AWS access denied when running download_plugins.sh

### ISSUE THREAD

**Issue by irslon** [opendistro-for-elasticsearch/opendistro-build#378]
I would like to build docker images on my own for future contributions.
I can't download plugins using download_plugins.sh resulting with Access Denied.
Should I have some special permissions to the s3 bucket to download them?  I'm logged in on my personal credentials on AWS CLI.

```
$ bash download_plugin.sh
[..]
++ aws s3api list-objects --bucket artifacts.opendistroforelasticsearch.amazon.com --prefix downloads/elasticsearch-plugins/opendistro-sql/opendistro_sql-1.10.0 --query 'Contents[].[Key]' --output text
++ sort
++ tail -n 1

An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

**Comment by peterzhuamazon** [comment]
Hi @irslon,
As of now, we have not decouple the scripts with our own credentials on AWS.
We are planning to do that in the future so everyone can create a distro by running these scripts.

Sorry about the inconvenience.
Thanks.

**Comment by peterzhuamazon** [comment]
Hi @irslon,
It has been nearly a month since we last talk.
This issue will be closed for now, but please feel free to re-open if you have more questions to this topic.

**Comment by nperon** [comment]
Hello @peterzhuamazon 

I have just created an issue in the opendistro forum on the same topic:
https://discuss.opendistrocommunity.dev/t/open-distro-build-with-plugins/4271
I am interested in a solution on how to build the docker images including plugins.
The two builds download_kibana_plugins.sh and download_plugins.sh do not work at the moment. 
I would like a workaround so that the plugins are included in the build. Can you give me 
a practical example for one plugin on where to copy the plugin source in the opendistro-build project ? 
And then how it needs to be referenced in the project, for instance in a fille called 
kibana/docker/build/kibana/plugins/plugins_kibana.list 

Best regards.

**Comment by peterzhuamazon** [comment]
Hi @nperon like we talked last time we are building a new solution for both us and users to build distros on their local.
However, this is a rather long term project as many of the structures/scripts/workflows require rewrite.
We are not having a defined date on the release of this. Please stay tune.

In the meantime, you are welcomed to directly create a new dockerfile based on our image and do modifications.
That should be a workaround before we introduce the new structure.
Sorry about the inconvinience you experience here.

Thanks.
