### ISSUE TITLE
Changes are not applied in 1.0.0 version using docker

### ISSUE THREAD

**Issue by orest-gulman** [opendistro-for-elasticsearch/opendistro-build#6]
All configuration files stores in my host machine, and replaced inside of containers by volumes:

```
 volumes:
-./roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
-./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
-./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
-./config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
```

After editing configuration files in a host machine, and restarting nodes, It doesn't apply any changes. The files actually replaced inside of containers, but nothing changed.

**Comment by dbroadhurst** [comment]
Same here. This seems like a really big issue, is anyone using opendistro?

**Comment by alolita** [comment]
Hi @dbroadhurst @orest-gulman Thanks for reporting. We'll take a look and see if we can replicate this issue.

**Comment by allenyin96** [comment]
Hi,

This is an expected behavior for security plugin. 

On startup, the security plugin will create an index, .opendistro_security, which stores the security related configs. If you modify the config files and restart the node, the same index will be picked up again by elasticsearch and the changes will not be reflected.

The recommended way to apply config changes is documented [here](https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/security-admin/). This allows you to apply the config changes without restarting the node.

You can also delete the .opendistro_security index and restart the node.

**Comment by dbroadhurst** [comment]
Thanks for the update. Yes, this makes sense. I tore down my container and it worked as expected.

**Comment by orest-gulman** [comment]
@allenyin96 Thank you!
