### ISSUE TITLE
allow environment variables to override UID 1000 in docker-entrypoint.sh

### ISSUE THREAD

**Issue by mmguero** [opendistro-for-elasticsearch/opendistro-build#613]
The entrypoint script [docker-entrypoint.sh](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/docker/build/elasticsearch/bin/docker-entrypoint.sh) has various checks to drop privileges, which is a good thing from a best-practices security point of view.

However, the UID 1000 is hard-coded in that script (search 1000 in that script). While this may work in a majority of users' situations, there are cases in which it's desirable that processes and file permissions are for another use (e.g., 1001, etc.). This UID value would need to be specifiable at runtime, not container build-time.

This could be easily resolved by allowing an environment variable to be checked and used, if specified, in docker-entrypoint.sh. In places where you'd use the 1000 UID, use something like:

```
${PUID:-1000}
```

Then, via a docker-compose.yml file or a docker run command a user could easily specify something like `--env PUID=1001`.

**Comment by peterzhuamazon** [comment]
Hi @MMakaria this is a valid suggestion and we appreciate if you can also create a PR for it.
However, it is unlikely that we will include this in the upcoming 1.13.0 release since we are already in the process.
We would review it after the release.

Thanks.

**Comment by camerski** [comment]
Hi @mmguero,

I'm working on updating the Docker files as part of https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696. I'm thinking that an easier solution is to not allowing running the entrypoint as root, and to use `docker run --user=whatever` to specify custom UIDs.

That achieves your purpose, using `--user=` rather than `--env PUID=`. Failing the script if run as root achieves the security best-practice goal.

I will also add build-time args to the Dockerfile so people can customize the default UID and GID.

Thoughts?

**Comment by mmguero** [comment]
Yes, I think that would be a fine solution. Thank you!

**Comment by camerski** [comment]
Great!

Here's the first part of the change: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/709

Feedback appreciated.

**Comment by camerski** [comment]
Resolved with https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/719
