### ISSUE TITLE
Fresh code base for opendistro

### ISSUE THREAD

**Issue by emikg777** [opendistro-for-elasticsearch/opendistro-build#723]
**Query**
Hello, will you have plans to synchronize code base between opendistro and elasticsearch(I mean update code base to 7.12 and etc). 

**Expected Behavior**
Fresh version of elasticsearch code base in opendistro

**Current Behavior**
Unknown

**Comment by gaiksaya** [comment]
Hi @emikg777,
Due to the recent licensing change in ElasticSearch we will not be updating OpenDistro to include any new ElasticSearch code beyond 7.10.2 version.
See https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/ for more details of what is happening. Also please check our discussion [forum](https://discuss.opendistrocommunity.dev/t/march-31-fork-update/5494)

Thanks!

**Comment by bbarani** [comment]
Hi @emikg777, I am closing this issue. Please feel free to re-open it if you need additional information.
